source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'
project 'XYChartDemo.xcodeproj'

install! 'cocoapods',
  :deterministic_uuids => false,
  :warn_for_unused_master_specs_repo => false

target 'XYChartDemo' do
  pod 'XYChart', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
