# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XYChart' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'XYChart', :path => '../'
  pod "FORGestureTrackDisplay"


  target 'XYChartTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XYChartUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
