name: XYChartDemo

options:
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "13.0"

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.xcodeyang.XYChartDemo
    PRODUCT_NAME: $(TARGET_NAME)
    INFOPLIST_FILE: Sources/Info.plist
    GENERATE_INFOPLIST_FILE: NO
    IPHONEOS_DEPLOYMENT_TARGET: "13.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
    CLANG_ENABLE_OBJC_ARC: YES

targets:
  XYChartDemo:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: ""

schemes:
  XYChartDemo:
    build:
      targets:
        XYChartDemo: all
    run:
      config: Debug
